### ISSUE TITLE
Trying to connect from a file:// URI fails makes server respond with corrupt http

### ISSUE THREAD

**Issue by michielbdejong** [5apps/liquor-cabinet#52]
Try setting redirect_uri parameter in the OAuth dialog to a file:// URL and setting the client_id to null. You end up with a 302 whose Location header is illegal because it tries to redirect you to the file URL, and this looks very ugly in the browser.

Instead, the OAuth dialog should already display a meaningful error message, and not even offer to click 'Allow'

**Comment by skddc** [comment]
There are no restrictions to URLs in the protocol and you cannot set the client_id to null, because that's the string "null".

We do show errors when you e.g. don't use a client ID.

In any case, this has nothing to do with liquor-cabinet, because LQ doesn't do any OAuth or Webfinger or anything except pure HTTP REST.

For 5apps Storage, you can open isssues on http://help.5apps.com/ (be sure to log in first by clicking the link in the top right corner).
