### ISSUE TITLE
URL Encoded UTF-8 characters in public file name cause a 500 error?

### ISSUE THREAD

**Issue by gregkare** [5apps/liquor-cabinet#92]
https://app.getsentry.com/5apps/liquor-cabinet/issues/145673307/

```
RestClient::InternalServerError: 500 Internal Server Error
  restclient/abstract_response.rb:223:in `exception_with_response'
    raise klass.new(self, code)
  restclient/abstract_response.rb:103:in `return!'
    raise exception_with_response
  restclient/request.rb:860:in `process_result'
    response.return!(&block)
  restclient/request.rb:776:in `block in transmit'
    process_result res, & block
  net/http.rb:853:in `start'
    return yield(self)
...
(46 additional frame(s) were not displayed)

RestClient::InternalServerError: 500 Internal Server Error
```

**Comment by gregkare** [comment]
It looks like it's the colon in the filename (`public/shares/160430-1701-Capture d'écran vidéo de 30-04-2016 18:59:26.webm`). In fact I just tried to reproduce this and it turns out you can't create a filename containing a colon on Mac OS X.

**Comment by galfert** [comment]
Looks like this exception might not be due to the filename. The file (https://storage.5apps.com/hugo/public/shares/160430-1701-Capture%20d%27%C3%A9cran%20vid%C3%A9o%20de%2030-04-2016%2018%3A58%3A48.webm) loads fine without producing a new exception.

I also dowloaded the file and uploaded it to my own storage without any problems.

**Comment by galfert** [comment]
I just resolved the Sentry issue, so we get notified if this happens again.
